version: '3'
services:
  volumes-provisioner:
    image: hasnat/volumes-provisioner
    environment:
      PROVISION_DIRECTORIES: >-
        ${USER_ID}:${USER_ID}:0777:/files;
        ${USER_ID}:${USER_ID}:0777:/mongo_db;
        ${USER_ID}:${USER_ID}:0777:/be_teams;
        ${USER_ID}:${USER_ID}:0777:/be_inventory;
        ${USER_ID}:${USER_ID}:0777:/be_control"
    volumes:
      - "./files:/files"
      - "./files/mongo_db:/mongo_db"
      - "./files/backend_log:/be_log"
      - "./files/backend_teams:/be_teams"
      - "./files/backend_inventory:/be_inventory"
      - "./files/backend_control:/be_control"
    network_mode: none
    command: sh -c "mkdir /mongo_log/loggo"
  database:
    depends_on:
      - volumes-provisioner
    image: mongo:latest
    restart: always
    volumes:
      - "./files/mongo_db:/db"
    ports:
      - "27017:27017"
    command: --dbpath=/db #--auth
    network_mode: host
  backend:
    depends_on:
      - database
    build:
      context: ./
      dockerfile: ./Dockerfile_backend
    restart: always
    environment:
      - GANTREE_OVERRIDE_INVENTORY_PATH=/inventory
    env_file:
      - ./env/backend
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      WAIT_HOSTS: localhost:27017
      GRAPHQL_PORT: "4000"
      SOCKETIO_PORT: "3000"
      MONGODB_URL: mongodb://localhost:27017/gantree
      APP_URL: http://localhost:5000
      TEAMSTORAGE_ROOT: /teams
    volumes:
      - "./files/backend_log:/log"
      - "./files/backend_teams:/teams"
      - "./files/backend_inventory:/inventory"
      - "./files/backend_control:/control"
    command: sh -c "eval `ssh-agent -s` && pm2 start process.yml && tail -f /dev/null"
    network_mode: host
  frontend:
    depends_on:
      - backend
    build:
      context: ./
      dockerfile: ./Dockerfile_frontend
    ports:
      - "5000:5000"
      - "443:443"
    environment:
      WAIT_HOSTS: localhost:3000, localhost:4000
    network_mode: host
    working_dir: /frontend
    #command: yarn dev
    command: sh -c "/wait && yarn dev"